PUT http://localhost:3001/games/1 HTTP/1.1
content-type: application/json

{
  "game": {
    "found_characters": [
      {
        "id": 9,
        "name": "Lupin III",
        "x_coordinate": 0.5422993492407809,
        "y_coordinate": 0.7516541685046316
      },
      {
        "id": 10,
        "name": "Casper",
        "x_coordinate": 0.1475054229934924,
        "y_coordinate": 0.3239964711071901
      },
      {
        "id": 11,
        "name": "Patrick",
        "x_coordinate": 0.6623270951993491,
        "y_coordinate": 0.8562740474121882
      },
      {
        "id": 12,
        "name": "Ash",
        "x_coordinate": 0.028199566160520606,
        "y_coordinate": 0.9186149095721218
      }
    ]
  }
}
